### ISSUE TITLE
Поиск не обрабатывает символ *

### ISSUE THREAD

**Issue by Elevoid** [lesqm/Database#5]
Запрос поиска по символу "*" выдает ошибку:

org.sql2o.Sql2oException: Database error: syntax error, unexpected $end, expecting FTS_TERM or FTS_NUMB or '*'

org.sql2o.Query$ResultSetIterableBase.(Query.java:332)
org.sql2o.Query$10.(Query.java:412)
org.sql2o.Query.executeAndFetchLazy(Query.java:412)
org.sql2o.Query.executeAndFetch(Query.java:454)
org.sql2o.Query.executeAndFetch(Query.java:441)
ru.lesqm.db.logic.Database.searchMilecule(Database.java:49)
ru.lesqm.db.controllers.SearchController.search(SearchController.java:25)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:497)
com.bunjlabs.fugaframework.router.Router.invoke(Router.java:130)
com.bunjlabs.fugaframework.router.Router.forward(Router.java:114)
com.bunjlabs.fugaframework.router.Router.forward(Router.java:73)
com.bunjlabs.fugaframework.network.HttpServerHandler.writeResponse(HttpServerHandler.java:193)
com.bunjlabs.fugaframework.network.HttpServerHandler.channelRead0(HttpServerHandler.java:122)
com.bunjlabs.fugaframework.network.HttpServerHandler.channelRead0(HttpServerHandler.java:50)
io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
java.lang.Thread.run(Thread.java:745)

**Comment by Show-vars** [comment]
Сейчас используется полнотекстовый поиск Mysql в логическом режиме. Символ `*` там означает совсем другое и его нужно использовать в других случаях.

Список поддерживаемых операторов из [официальной документации](http://www.mysql.ru/docs/man/Fulltext_Search.html):

```
+ Предшествующий слову знак ``плюс'' показывает, что это слово должно присутствовать в каждой возвращенной строке.
- Предшествующий слову знак ``минус'' означает, что это слово не должно присутствовать в какой-либо возвращенной строке.
По умолчанию (если ни плюс, ни минус не указаны) данное слово является не обязательным, но содержащие его строки будут оцениваться более высоко. Это имитирует поведение команды MATCH() ... AGAINST() без модификатора IN BOOLEAN MODE.
< > Эти два оператора используются для того, чтобы изменить вклад слова в величину релевантности, которое приписывается строке. Оператор < уменьшает этот вклад, а оператор > - увеличивает его. 
( ) Круглые скобки группируют слова в подвыражения.
~ Предшествующий слову знак ``тильда'' воздействует как оператор отрицания, обуславливая негативный вклад данного слова в релевантность строки. Им отмечают нежелательные слова. Строка, содержащая такое слово, будет оценена ниже других, но не будет исключена совершенно, как в случае оператора - ``минус''.
* Звездочка является оператором усечения. В отличие от остальных операторов, она должна добавляться в конце слова, а не в начале.
" Фраза, заключенная в двойные кавычки, соответствует только строкам, содержащим эту фразу, написанную буквально.
```
